In [1]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

C:\Users\COM\20190427\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\COM\20190427\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
dataset=pd.read_csv("C:/Users/COM/Desktop/python class/machineLearningBasic-master/machineLearningBasic-master/datasets/Social_Network_Ads.csv")

In [8]:
df=dataset

In [10]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [16]:
x=df.iloc[:,[2,3]].values.astype("float32")
y=df.iloc[:,4].values.astype("float32")

In [17]:
xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.2)

In [20]:
sc=StandardScaler()

In [22]:
xtr

array([[4.50e+01, 7.90e+04],
       [2.60e+01, 7.20e+04],
       [4.20e+01, 8.00e+04],
       [4.70e+01, 4.30e+04],
       [3.00e+01, 6.20e+04],
       [4.90e+01, 8.80e+04],
       [4.20e+01, 1.08e+05],
       [3.70e+01, 7.10e+04],
       [4.00e+01, 5.70e+04],
       [5.90e+01, 4.20e+04],
       [3.90e+01, 7.10e+04],
       [4.20e+01, 7.30e+04],
       [4.10e+01, 7.20e+04],
       [4.70e+01, 1.07e+05],
       [3.70e+01, 1.37e+05],
       [3.50e+01, 3.90e+04],
       [4.90e+01, 6.50e+04],
       [4.20e+01, 5.40e+04],
       [2.70e+01, 8.40e+04],
       [3.90e+01, 1.34e+05],
       [3.20e+01, 1.35e+05],
       [2.00e+01, 4.90e+04],
       [5.20e+01, 1.38e+05],
       [3.40e+01, 4.30e+04],
       [3.80e+01, 5.00e+04],
       [5.20e+01, 2.10e+04],
       [3.00e+01, 1.16e+05],
       [3.70e+01, 7.50e+04],
       [4.90e+01, 2.80e+04],
       [3.20e+01, 1.20e+05],
       [1.90e+01, 7.00e+04],
       [3.50e+01, 5.00e+04],
       [2.90e+01, 7.50e+04],
       [4.10e+01, 5.10e+04],
       [3.50e+

In [27]:
xtr_sc=sc.fit_transform(xtr)
xte_sc=sc.transform(xte)
#fit을 두번하면 스케일 기준이 변경되어 fit은 한번만
lr_clf=LogisticRegression()
lr_clf.fit(xtr_sc,ytr)

C:\Users\COM\20190427\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
y_pred=lr_clf.predict(xte_sc)

In [30]:
y_pred_pro=lr_clf.predict_proba(xte_sc)

In [36]:
y_pred

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [41]:
a=pd.DataFrame(y_pred_pro)

In [42]:
a['label']=y_pred

0         1  label
0   0.176102  0.823898    1.0
1   0.552494  0.447506    0.0
2   0.758211  0.241789    0.0
3   0.980476  0.019524    0.0
4   0.709924  0.290076    0.0
5   0.136360  0.863640    1.0
6   0.995797  0.004203    0.0
7   0.570117  0.429883    0.0
8   0.584547  0.415453    0.0
9   0.098577  0.901423    1.0
10  0.848226  0.151774    0.0
11  0.772549  0.227451    0.0
12  0.025957  0.974043    1.0
13  0.822743  0.177257    0.0
14  0.993338  0.006662    0.0
15  0.706151  0.293849    0.0
16  0.989362  0.010638    0.0
17  0.984270  0.015730    0.0
18  0.077700  0.922300    1.0
19  0.600958  0.399042    0.0
20  0.592711  0.407289    0.0
21  0.021391  0.978609    1.0
22  0.998020  0.001980    0.0
23  0.998435  0.001565    0.0
24  0.035438  0.964562    1.0
25  0.719222  0.280778    0.0
26  0.808793  0.191207    0.0
27  0.697478  0.302522    0.0
28  0.199428  0.800572    1.0
29  0.065426  0.934574    1.0
..       ...       ...    ...
50  0.714059  0.285941    0.0
51  0.273487  0.726513    1.0
52  0.286126  0.713874    1.0
53  0.080110  0.919890    1.0
54  0.545311  0.454689    0.0
55  0.461226  0.538774    1.0
56  0.460058  0.539942    1.0
57  0.492652  0.507348    1.0
58  0.011021  0.988979    1.0
59  0.992902  0.007098    0.0
60  0.041322  0.958678    1.0
61  0.631723  0.368277    0.0
62  0.994170  0.005830    0.0
63  0.888398  0.111602    0.0
64  0.586694  0.413306    0.0
65  0.649284  0.350716    0.0
66  0.995193  0.004807    0.0
67  0.922996  0.077004    0.0
68  0.997262  0.002738    0.0
69  0.918995  0.081005    0.0
70  0.951527  0.048473    0.0
71  0.963734  0.036266    0.0
72  0.451833  0.548167    1.0
73  0.994503  0.005497    0.0
74  0.332159  0.667841    1.0
75  0.679342  0.320658    0.0
76  0.902602  0.097398    0.0
77  0.910127  0.089873    0.0
78  0.923875  0.076125    0.0
79  0.987638  0.012362    0.0

[80 rows x 3 columns]

In [34]:
y_pred_pro>0.6  #임계값 조정 디폴트는 0.5

array([[False,  True],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [False, False],
       [False,  True],
       [ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ Tr

In [39]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(yte,y_pred,labels=[1,0]))

[[21  8]
 [ 1 50]]
